export const paramsList = {
  "pod-scenarios": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText:
        "Prefix openshift- to pick and disrupt pods randomly in openshift system namespaces",
      isRequired: true,
    },
    {
      key: "pod_label",
      label: "POD Label",
      fieldId: "pod_label-id",
      ariaDescribedby: "pod label",
      helperText: "",
      isRequired: false,
    },
    {
      key: "name_pattern",
      label: "Name Pattern",
      fieldId: "name_pattern-id",
      ariaDescribedby: "name pattern",
      helperText: "",
      isRequired: false,
    },
    {
      key: "disruption_count",
      label: "Disruption Count",
      fieldId: "disruption_count-id",
      ariaDescribedby: "disruption count",
      helperText: "",
      isRequired: false,
    },
    {
      key: "kill_timeout",
      label: "Kill Timeout",
      fieldId: "kill_timeout-id",
      ariaDescribedby: "kill timeout",
      helperText: "",
      isRequired: false,
    },
    {
      key: "wait_timeout",
      label: "Wait Timeout",
      fieldId: "wait_timeout-id",
      ariaDescribedby: "wait timeout",
      helperText: "",
      isRequired: false,
    },
    {
      key: "expected_pod_count",
      label: "Expected POD count",
      fieldId: "expected_pod_count-id",
      ariaDescribedby: "expected pod count",
      helperText: "",
      isRequired: false,
    },
  ],
  "container-scenarios": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText:
        "Prefix openshift- to pick and disrupt pods randomly in openshift system namespaces",
      isRequired: true,
    },
    {
      key: "label_selector",
      label: "Label Selector",
      fieldId: "label-selector-id",
      ariaDescribedby: "label selector",
      helperText: "",
      isRequired: true,
    },
    {
      key: "disruption_count",
      label: "Disruption Count",
      fieldId: "disruption_count-id",
      ariaDescribedby: "disruption count",
      helperText: "",
      isRequired: true,
    },
    {
      key: "container_name",
      label: "CONTAINER_NAME",
      fieldId: "container_name-id",
      ariaDescribedby: "container_name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "action",
      label: "Action",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "",
      isRequired: true,
    },
    {
      key: "expected_recovery_time",
      label: "Expected recovery time",
      fieldId: "expected_recovery_time-id",
      ariaDescribedby: "expected_recovery_time",
      helperText: "",
      isRequired: true,
    },
  ],
  "namespace-scenarios": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "action",
      label: "ACTION",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "",
      isRequired: true,
    },
    {
      key: "label-selector",
      label: "LABEL_SELECTOR",
      fieldId: "label-selector-id",
      ariaDescribedby: "label selector",
      helperText: "",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText:
        "Prefix openshift- to pick and disrupt pods randomly in openshift system namespaces",
      isRequired: true,
    },
    {
      key: "sleep",
      label: "SLEEP",
      fieldId: "sleep-id",
      ariaDescribedby: "sleep",
      helperText: "",
      isRequired: true,
    },
    {
      key: "delete_count",
      label: "DELETE_COUNT",
      fieldId: "delete_count-id",
      ariaDescribedby: "delete_count",
      helperText: "",
      isRequired: true,
    },
    {
      key: "runs",
      label: "RUNS",
      fieldId: "runs-id",
      ariaDescribedby: "runs",
      helperText: "",
      isRequired: true,
    },
  ],
  "node-scenarios": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "action",
      label: "Action",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "e.g. node_stop_start_scenario",
      isRequired: true,
    },
    {
      key: "cloud_type",
      label: "Cloud Type",
      fieldId: "cloud_type-id",
      ariaDescribedby: "cloud type",
      helperText: "e.g. aws, gcp, azure, openstack, baremetal",
      isRequired: true,
    },
    {
      key: "label_selector",
      label: "Label Selector",
      fieldId: "label_selector-id",
      ariaDescribedby: "label selector",
      helperText: "e.g. node-role.kubernetes.io/worker",
      isRequired: false,
    },
    {
      key: "node_name",
      label: "Node Name",
      fieldId: "node_name-id",
      ariaDescribedby: "node name",
      helperText: "Specific node name; overrides label selector when set",
      isRequired: false,
    },
    {
      key: "instance_count",
      label: "Instance Count",
      fieldId: "instance_count-id",
      ariaDescribedby: "instance count",
      helperText: "",
      isRequired: false,
    },
    {
      key: "runs",
      label: "Runs",
      fieldId: "runs-id",
      ariaDescribedby: "runs",
      helperText: "",
      isRequired: false,
    },
    {
      key: "timeout",
      label: "Timeout",
      fieldId: "timeout-id",
      ariaDescribedby: "timeout",
      helperText: "Seconds to wait for node scenario completion",
      isRequired: false,
    },
    {
      key: "duration",
      label: "Duration",
      fieldId: "duration-id",
      ariaDescribedby: "duration",
      helperText: "Seconds to keep the node stopped before restarting",
      isRequired: false,
    },
  ],
  "pvc-scenarios": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "pvc_name",
      label: "PVC_NAME",
      fieldId: "pvc_name-id",
      ariaDescribedby: "pvc name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "pod_name",
      label: "POD_NAME",
      fieldId: "pod_name-id",
      ariaDescribedby: "pod_name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "NAMESPACE",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "",
      isRequired: true,
    },
    {
      key: "fill_percentage",
      label: "FILL_PERCENTAGE",
      fieldId: "fill_percentage-id",
      ariaDescribedby: "fill percentage",
      helperText: "",
      isRequired: false,
    },
    {
      key: "duration",
      label: "DURATION",
      fieldId: "duration-id",
      ariaDescribedby: "duration",
      helperText: "",
      isRequired: false,
    },
    {
      key: "block_size",
      label: "BLOCK_SIZE",
      fieldId: "block_size-id",
      ariaDescribedby: "block size",
      helperText: "Used by dd if fallocate is not present in the container",
      isRequired: false,
    },
  ],
  "time-scenarios": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "object_type",
      label: "OBJECT_TYPE",
      fieldId: "object_type-id",
      ariaDescribedby: "object_type",
      helperText: "",
      isRequired: true,
    },
    {
      key: "label_selector",
      label: "LABEL_SELECTOR",
      fieldId: "label_selector-id",
      ariaDescribedby: "label_selector",
      helperText: "",
      isRequired: true,
    },
    {
      key: "action",
      label: "ACTION",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "",
      isRequired: true,
    },
    {
      key: "object_name",
      label: "OBJECT_NAME",
      fieldId: "object_name-id",
      ariaDescribedby: "object_name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "container_name",
      label: "CONTAINER_NAME",
      fieldId: "container_name-id",
      ariaDescribedby: "container_name",
      helperText: "",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "NAMESPACE",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "",
      isRequired: false,
    },
  ],
  "power-outages": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "shutdown_duration",
      label: "SHUTDOWN_DURATION",
      fieldId: "shutdown_duration-id",
      ariaDescribedby: "shutdown_duration",
      helperText: "",
      isRequired: true,
    },
    {
      key: "cloud_type",
      label: "CLOUD_TYPE",
      fieldId: "cloud_type-id",
      ariaDescribedby: "cloud_type",
      helperText: "",
      isRequired: true,
    },
    {
      key: "timeout",
      label: "TIMEOUT",
      fieldId: "timeout-id",
      ariaDescribedby: "timeout",
      helperText: "",
      isRequired: true,
    },
  ],
  "node-cpu-hog": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "total_chaos_duration",
      label: "Total Chaos duration",
      fieldId: "total_chaos_duration-id",
      ariaDescribedby: "total chaos duration",
      helperText: "",
      isRequired: true,
    },
    {
      key: "node_cpu_core",
      label: "Node cpu core",
      fieldId: "node_cpu_core-id",
      ariaDescribedby: "node cpu core",
      helperText: "",
      isRequired: true,
    },
    {
      key: "node_cpu_percentage",
      label: "Node CPU Percentage",
      fieldId: "node_cpu_percentage-id",
      ariaDescribedby: "node cpu percentage",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "",
      isRequired: true,
    },
    {
      key: "node_selectors",
      label: "Node selectors",
      fieldId: "node_selectors-id",
      ariaDescribedby: "node selectors",
      helperText:
        "Node selectors where the scenario containers will be scheduled in the format <selector>=<value>",
      isRequired: false,
    },
  ],
  "node-io-hog": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "total_chaos_duration",
      label: "Total Chaos duration",
      fieldId: "total_chaos_duration-id",
      ariaDescribedby: "total chaos duration",
      helperText: "",
      isRequired: true,
    },
    {
      key: "io_block_size",
      label: "IO Block Size",
      fieldId: "io_block_size-id",
      ariaDescribedby: "ioblock size",
      helperText: "",
      isRequired: true,
    },
    {
      key: "io_workers",
      label: "IO Workers",
      fieldId: "io_workers-id",
      ariaDescribedby: "io workers",
      helperText: "",
      isRequired: true,
    },
    {
      key: "io_write_bytes",
      label: "IO Write bytes",
      fieldId: "io_write_bytes-id",
      ariaDescribedby: "io write bytes",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "",
      isRequired: true,
    },
    {
      key: "node_selectors",
      label: "Node selectors",
      fieldId: "node_selectors-id",
      ariaDescribedby: "node selectors",
      helperText:
        "Node selectors where the scenario containers will be scheduled in the format <selector>=<value>",
      isRequired: false,
    },
  ],
  "node-memory-hog": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "total_chaos_duration",
      label: "Total Chaos duration",
      fieldId: "total_chaos_duration-id",
      ariaDescribedby: "total chaos duration",
      helperText: "",
      isRequired: true,
    },
    {
      key: "memory_consumption_percentage",
      label: "Memory Consumption percentage",
      fieldId: "memory_consumption_percentage-id",
      ariaDescribedby: "memory consumption percentage",
      helperText: "",
      isRequired: true,
    },
    {
      key: "number_of_workers",
      label: "Number of workers",
      fieldId: "number_of_workers-id",
      ariaDescribedby: "number of workers",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "",
      isRequired: true,
    },
    {
      key: "node_selectors",
      label: "Node selectors",
      fieldId: "node_selectors-id",
      ariaDescribedby: "node selectors",
      helperText:
        "Node selectors where the scenario containers will be scheduled in the format <selector>=<value>",
      isRequired: false,
    },
  ],
  "zone-outages": [
    {
      key: "name",
      label: "Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "cloud_type",
      label: "Cloud Type",
      fieldId: "cloud_type-id",
      ariaDescribedby: "cloud type",
      helperText: "e.g. aws, gcp",
      isRequired: true,
    },
    {
      key: "duration",
      label: "Duration",
      fieldId: "duration-id",
      ariaDescribedby: "duration",
      helperText: "Seconds after which the zone will be back online",
      isRequired: false,
    },
    {
      key: "vpc_id",
      label: "VPC ID",
      fieldId: "vpc_id-id",
      ariaDescribedby: "vpc id",
      helperText: "Required for AWS",
      isRequired: false,
    },
    {
      key: "subnet_id",
      label: "Subnet ID",
      fieldId: "subnet_id-id",
      ariaDescribedby: "subnet id",
      helperText: "Required for AWS. Format: [subnet1, subnet2]",
      isRequired: false,
    },
    {
      key: "zone",
      label: "Zone",
      fieldId: "zone-id",
      ariaDescribedby: "zone",
      helperText: "Required for GCP",
      isRequired: false,
    },
    {
      key: "default_acl_id",
      label: "Default ACL ID",
      fieldId: "default_acl_id-id",
      ariaDescribedby: "default acl id",
      helperText:
        "Optional AWS-only: reuse an existing network ACL instead of creating one",
      isRequired: false,
    },
  ],
};
