export const paramsList = {
  "pod-scenarios": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Targeted namespace in the cluster ( supports regex )",
      defaultValue: "openshift-.*",
      isRequired: false,
    },
    {
      key: "node_names",
      label: "Node Names",
      fieldId: "node_names-id",
      ariaDescribedby: "node names",
      helperText: "Node names to target",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "node_label_selector",
      label: "Node Label Selector",
      fieldId: "node_label_selector-id",
      ariaDescribedby: "node label selector",
      helperText: "Label selector to target nodes",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "pod_label",
      label: "Pod Label",
      fieldId: "pod_label-id",
      ariaDescribedby: "pod label",
      helperText: "Label of the pod(s) to target",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "exclude_label",
      label: "Exclude Label",
      fieldId: "exclude_label-id",
      ariaDescribedby: "exclude label",
      helperText: "Label for excluding one or more pods from chaos",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "name_pattern",
      label: "Name Pattern",
      fieldId: "name_pattern-id",
      ariaDescribedby: "name pattern",
      helperText: "Regex pattern to match the pods in NAMESPACE when POD_LABEL is not specified",
      defaultValue: ".*",
      isRequired: false,
    },
    {
      key: "disruption_count",
      label: "Disruption Count",
      fieldId: "disruption_count-id",
      ariaDescribedby: "disruption count",
      helperText: "Number of pods to disrupt",
      defaultValue: "1",
      isRequired: false,
    },
    {
      key: "kill_timeout",
      label: "Kill Timeout",
      fieldId: "kill_timeout-id",
      ariaDescribedby: "kill timeout",
      helperText: "Timeout to wait for the target pod(s) to be removed in seconds",
      defaultValue: "180",
      isRequired: false,
    },
    {
      key: "expected_recovery_time",
      label: "Expected Recovery Time",
      fieldId: "expected_recovery_time-id",
      ariaDescribedby: "expected recovery time",
      helperText: "Fails if the pod disrupted do not recover within the timeout set",
      defaultValue: "120",
      isRequired: false,
    },
  ],
  "container-scenarios": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Targeted namespace in the cluster",
      defaultValue: "openshift-etcd",
      isRequired: false,
    },
    {
      key: "label_selector",
      label: "Label Selector",
      fieldId: "label-selector-id",
      ariaDescribedby: "label selector",
      helperText: "Label of the container(s) to target",
      defaultValue: "k8s-app=etcd",
      isRequired: false,
    },
    {
      key: "exclude_label",
      label: "Exclude Label",
      fieldId: "exclude_label-id",
      ariaDescribedby: "exclude label",
      helperText: 'Pods to exclude from targeting. For example "{app: foo}"',
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "disruption_count",
      label: "Disruption Count",
      fieldId: "disruption_count-id",
      ariaDescribedby: "disruption count",
      helperText: "Number of container to disrupt",
      defaultValue: "1",
      isRequired: false,
    },
    {
      key: "container_name",
      label: "Container Name",
      fieldId: "container_name-id",
      ariaDescribedby: "container name",
      helperText: "Name of the container to disrupt",
      defaultValue: "etcd",
      isRequired: false,
    },
    {
      key: "action",
      label: "Action",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "Kill signal to run. For example 1 ( hang up ) or 9",
      defaultValue: "1",
      isRequired: false,
    },
    {
      key: "expected_recovery_time",
      label: "Expected Recovery Time",
      fieldId: "expected_recovery_time-id",
      ariaDescribedby: "expected recovery time",
      helperText: "Time to wait before checking if all containers that were affected recover properly",
      defaultValue: "60",
      isRequired: false,
    },
  ],
  "namespace-scenarios": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "action",
      label: "Action",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "",
      isRequired: true,
    },
    {
      key: "label-selector",
      label: "Label Selector",
      fieldId: "label-selector-id",
      ariaDescribedby: "label selector",
      helperText: "",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Prefix openshift- to pick and disrupt pods randomly in openshift system namespaces",
      isRequired: true,
    },
    {
      key: "sleep",
      label: "Sleep",
      fieldId: "sleep-id",
      ariaDescribedby: "sleep",
      helperText: "",
      isRequired: true,
    },
    {
      key: "delete_count",
      label: "Delete Count",
      fieldId: "delete_count-id",
      ariaDescribedby: "delete count",
      helperText: "",
      isRequired: true,
    },
    {
      key: "runs",
      label: "Runs",
      fieldId: "runs-id",
      ariaDescribedby: "runs",
      helperText: "",
      isRequired: true,
    },
  ],
  "node-scenarios": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "action",
      label: "Action",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "Action performed on the node. Visit https://github.com/krkn-chaos/krkn/blob/main/docs/node_scenarios.md for more info",
      defaultValue: "node_stop_start_scenario",
      isRequired: true,
    },
    {
      key: "label_selector",
      label: "Label Selector",
      fieldId: "label_selector-id",
      ariaDescribedby: "label selector",
      helperText: "Node label to target",
      defaultValue: "node-role.kubernetes.io/worker",
      isRequired: false,
    },
    {
      key: "exclude_label",
      label: "Exclude Label",
      fieldId: "exclude_label-id",
      ariaDescribedby: "exclude label",
      helperText: "Label for excluding one or more nodes from chaos",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "node_name",
      label: "Node Name",
      fieldId: "node_name-id",
      ariaDescribedby: "node name",
      helperText: "Node name to inject faults in case of targeting a specific node; Can set multiple node names separated by a comma",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "instance_count",
      label: "Instance Count",
      fieldId: "instance_count-id",
      ariaDescribedby: "instance count",
      helperText: "Targeted instance count matching the label selector",
      defaultValue: "1",
      isRequired: false,
    },
    {
      key: "runs",
      label: "Runs",
      fieldId: "runs-id",
      ariaDescribedby: "runs",
      helperText: "Iterations to perform action on a single node",
      defaultValue: "1",
      isRequired: false,
    },
    {
      key: "kube_check",
      label: "Kube Check",
      fieldId: "kube_check-id",
      ariaDescribedby: "kube check",
      helperText: "Connect to the kubernetes api to see if the node gets to a certain state during the node scenario",
      defaultValue: "true",
      isRequired: false,
    },
    {
      key: "parallel",
      label: "Parallel",
      fieldId: "parallel-id",
      ariaDescribedby: "parallel",
      helperText: "Run action on label or node name in parallel or sequential, defaults to sequential (false)",
      defaultValue: "false",
      isRequired: false,
    },
    {
      key: "cloud_type",
      label: "Cloud Type",
      fieldId: "cloud_type-id",
      ariaDescribedby: "cloud type",
      helperText: "Cloud platform on top of which cluster is running, supported platforms - aws, azure, gcp, vmware, ibmcloud, bm",
      defaultValue: "aws",
      isRequired: false,
    },
    {
      key: "timeout",
      label: "Timeout",
      fieldId: "timeout-id",
      ariaDescribedby: "timeout",
      helperText: "Duration to wait for completion of node scenario injection",
      defaultValue: "180",
      isRequired: false,
    },
    {
      key: "duration",
      label: "Duration",
      fieldId: "duration-id",
      ariaDescribedby: "duration",
      helperText: "Duration to wait for completion of node scenario injection",
      defaultValue: "120",
      isRequired: false,
    },
    {
      key: "vsphere_ip",
      label: "VSphere IP",
      fieldId: "vsphere_ip-id",
      ariaDescribedby: "vsphere ip",
      helperText: "VSphere IP Address [VSphere only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "vsphere_username",
      label: "VSphere Username",
      fieldId: "vsphere_username-id",
      ariaDescribedby: "vsphere username",
      helperText: "VSphere Username [VSphere only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "vsphere_password",
      label: "VSphere Password",
      fieldId: "vsphere_password-id",
      ariaDescribedby: "vsphere password",
      helperText: "VSphere Password [VSphere only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "aws_access_key_id",
      label: "AWS Access Key ID",
      fieldId: "aws_access_key_id-id",
      ariaDescribedby: "aws access key id",
      helperText: "AWS Access Key ID [AWS only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "aws_secret_access_key",
      label: "AWS Secret Access Key",
      fieldId: "aws_secret_access_key-id",
      ariaDescribedby: "aws secret access key",
      helperText: "AWS Secret Access Key [AWS only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "aws_default_region",
      label: "AWS Default Region",
      fieldId: "aws_default_region-id",
      ariaDescribedby: "aws default region",
      helperText: "AWS Default Region [AWS only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "bmc_user",
      label: "BMC User",
      fieldId: "bmc_user-id",
      ariaDescribedby: "bmc user",
      helperText: "IPMI/BMC Username [Bare Metal only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "bmc_password",
      label: "BMC Password",
      fieldId: "bmc_password-id",
      ariaDescribedby: "bmc password",
      helperText: "IPMI/BMC Password [Bare Metal only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "bmc_addr",
      label: "BMC Address",
      fieldId: "bmc_addr-id",
      ariaDescribedby: "bmc address",
      helperText: "IPMI/BMC Address [Bare Metal only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "disks",
      label: "Disks",
      fieldId: "disks-id",
      ariaDescribedby: "disks",
      helperText: 'List of disks for baremetal nodes - format: ["sda", "sdb"] [Bare Metal only]',
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "ibmc_url",
      label: "IBM Cloud URL",
      fieldId: "ibmc_url-id",
      ariaDescribedby: "ibmc url",
      helperText: "IBM Cloud URL [IBM Cloud only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "ibmc_power_url",
      label: "IBM Cloud Power URL",
      fieldId: "ibmc_power_url-id",
      ariaDescribedby: "ibmc power url",
      helperText: "IBM Cloud Power URL [IBM Power Cloud only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "ibmc_power_crn",
      label: "IBM Cloud Power Workspace CRN",
      fieldId: "ibmc_power_crn-id",
      ariaDescribedby: "ibmc power crn",
      helperText: "IBM Cloud Power Workspace CRN [IBM Power Cloud only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "ibmc_apikey",
      label: "IBM Cloud API Key",
      fieldId: "ibmc_apikey-id",
      ariaDescribedby: "ibmc api key",
      helperText: "IBM Cloud API Key [IBM Cloud only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "disable_ssl_verification",
      label: "Disable SSL Verification",
      fieldId: "disable_ssl_verification-id",
      ariaDescribedby: "disable ssl verification",
      helperText: "Disable SSL certificate verification [IBM Cloud only]",
      defaultValue: "false",
      isRequired: true,
    },
    {
      key: "azure_tenant_id",
      label: "Azure Tenant ID",
      fieldId: "azure_tenant_id-id",
      ariaDescribedby: "azure tenant id",
      helperText: "Azure Tenant ID [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_client_secret",
      label: "Azure Client Secret",
      fieldId: "azure_client_secret-id",
      ariaDescribedby: "azure client secret",
      helperText: "Azure Client Secret [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_client_id",
      label: "Azure Client ID",
      fieldId: "azure_client_id-id",
      ariaDescribedby: "azure client id",
      helperText: "Azure Client ID [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_subscription_id",
      label: "Azure Subscription ID",
      fieldId: "azure_subscription_id-id",
      ariaDescribedby: "azure subscription id",
      helperText: "Azure Subscription ID [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "google_application_credentials",
      label: "GCP Application Credentials",
      fieldId: "google_application_credentials-id",
      ariaDescribedby: "gcp application credentials",
      helperText: "GCP application credentials file location [GCP only]",
      defaultValue: "",
      isRequired: false,
    },
  ],
  "pvc-scenarios": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "pvc_name",
      label: "PVC Name",
      fieldId: "pvc_name-id",
      ariaDescribedby: "pvc name",
      helperText: "Targeted PersistentVolumeClaim in the cluster (if null, POD_NAME is required)",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "pod_name",
      label: "Pod Name",
      fieldId: "pod_name-id",
      ariaDescribedby: "pod name",
      helperText: "Targeted pod in the cluster (if null, PVC_NAME is required)",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Targeted namespace in the cluster (required)",
      isRequired: true,
    },
    {
      key: "fill_percentage",
      label: "Fill Percentage",
      fieldId: "fill_percentage-id",
      ariaDescribedby: "fill percentage",
      helperText: "Targeted percentage to be filled up in the PVC",
      defaultValue: "50",
      isRequired: false,
    },
    {
      key: "duration",
      label: "Duration",
      fieldId: "duration-id",
      ariaDescribedby: "duration",
      helperText: "Duration in seconds with the PVC filled up",
      defaultValue: "60",
      isRequired: false,
    },
    {
      key: "block_size",
      label: "Block Size",
      fieldId: "block_size-id",
      ariaDescribedby: "block size",
      helperText: "Used by dd if fallocate is not present in the container",
      defaultValue: "",
      isRequired: false,
    },
  ],
  "time-scenarios": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "object_type",
      label: "Object Type",
      fieldId: "object_type-id",
      ariaDescribedby: "object type",
      helperText: "Object to target. Supported options: pod, node",
      defaultValue: "pod",
      isRequired: false,
    },
    {
      key: "label_selector",
      label: "Label Selector",
      fieldId: "label_selector-id",
      ariaDescribedby: "label selector",
      helperText: "Label of the container(s) or nodes to target",
      defaultValue: "k8s-app=etcd",
      isRequired: false,
    },
    {
      key: "action",
      label: "Action",
      fieldId: "action-id",
      ariaDescribedby: "action",
      helperText: "Action to run. Supported actions: skew_time, skew_date",
      defaultValue: "skew_date",
      isRequired: false,
    },
    {
      key: "object_name",
      label: "Object Name",
      fieldId: "object_name-id",
      ariaDescribedby: "object name",
      helperText: "List of the names of pods or nodes you want to skew",
      defaultValue: "[]",
      isRequired: false,
    },
    {
      key: "container_name",
      label: "Container Name",
      fieldId: "container_name-id",
      ariaDescribedby: "container name",
      helperText: "Container in the specified pod to target in case the pod has multiple containers running. Random container is picked if empty",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Namespace of the pods you want to skew, need to be set only if setting a specific pod name",
      defaultValue: "",
      isRequired: false,
    },
  ],
  "power-outages": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "shutdown_duration",
      label: "Shutdown Duration",
      fieldId: "shutdown_duration-id",
      ariaDescribedby: "shutdown duration",
      helperText: "Duration in seconds to shut down the cluster",
      defaultValue: "1200",
      isRequired: false,
    },
    {
      key: "cloud_type",
      label: "Cloud Type",
      fieldId: "cloud_type-id",
      ariaDescribedby: "cloud type",
      helperText: "Cloud platform on top of which cluster is running",
      defaultValue: "aws",
      isRequired: false,
    },
    {
      key: "timeout",
      label: "Timeout",
      fieldId: "timeout-id",
      ariaDescribedby: "timeout",
      helperText: "Time in seconds to wait for each node to be stopped or running after the cluster comes back",
      defaultValue: "600",
      isRequired: false,
    },
    {
      key: "vsphere_ip",
      label: "VSphere IP",
      fieldId: "vsphere_ip-id",
      ariaDescribedby: "vsphere ip",
      helperText: "VSphere IP Address [VSphere only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "vsphere_username",
      label: "VSphere Username",
      fieldId: "vsphere_username-id",
      ariaDescribedby: "vsphere username",
      helperText: "VSphere Username [VSphere only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "vsphere_password",
      label: "VSphere Password",
      fieldId: "vsphere_password-id",
      ariaDescribedby: "vsphere password",
      helperText: "VSphere Password [VSphere only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "aws_access_key_id",
      label: "AWS Access Key ID",
      fieldId: "aws_access_key_id-id",
      ariaDescribedby: "aws access key id",
      helperText: "AWS Access Key ID [AWS only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "aws_secret_access_key",
      label: "AWS Secret Access Key",
      fieldId: "aws_secret_access_key-id",
      ariaDescribedby: "aws secret access key",
      helperText: "AWS Secret Access Key [AWS only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "aws_default_region",
      label: "AWS Default Region",
      fieldId: "aws_default_region-id",
      ariaDescribedby: "aws default region",
      helperText: "AWS Default Region [AWS only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "bmc_user",
      label: "BMC User",
      fieldId: "bmc_user-id",
      ariaDescribedby: "bmc user",
      helperText: "IPMI/BMC Username [Bare Metal only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "bmc_password",
      label: "BMC Password",
      fieldId: "bmc_password-id",
      ariaDescribedby: "bmc password",
      helperText: "IPMI/BMC Password [Bare Metal only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "bmc_addr",
      label: "BMC Address",
      fieldId: "bmc_addr-id",
      ariaDescribedby: "bmc address",
      helperText: "IPMI/BMC Address [Bare Metal only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "ibmc_url",
      label: "IBM Cloud URL",
      fieldId: "ibmc_url-id",
      ariaDescribedby: "ibmc url",
      helperText: "IBM Cloud URL [IBM Cloud only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "ibmc_apikey",
      label: "IBM Cloud API Key",
      fieldId: "ibmc_apikey-id",
      ariaDescribedby: "ibmc api key",
      helperText: "IBM Cloud API Key [IBM Cloud only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_tenant_id",
      label: "Azure Tenant ID",
      fieldId: "azure_tenant_id-id",
      ariaDescribedby: "azure tenant id",
      helperText: "Azure Tenant ID [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_client_secret",
      label: "Azure Client Secret",
      fieldId: "azure_client_secret-id",
      ariaDescribedby: "azure client secret",
      helperText: "Azure Client Secret [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_client_id",
      label: "Azure Client ID",
      fieldId: "azure_client_id-id",
      ariaDescribedby: "azure client id",
      helperText: "Azure Client ID [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "azure_subscription_id",
      label: "Azure Subscription ID",
      fieldId: "azure_subscription_id-id",
      ariaDescribedby: "azure subscription id",
      helperText: "Azure Subscription ID [Azure only]",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "google_application_credentials",
      label: "GCP Application Credentials",
      fieldId: "google_application_credentials-id",
      ariaDescribedby: "gcp application credentials",
      helperText: "GCP application credentials file location [GCP only]",
      defaultValue: "",
      isRequired: false,
    },
  ],
  "node-cpu-hog": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "total_chaos_duration",
      label: "Total Chaos Duration",
      fieldId: "total_chaos_duration-id",
      ariaDescribedby: "total chaos duration",
      helperText: "Set chaos duration (in sec) as desired",
      defaultValue: "60",
      isRequired: false,
    },
    {
      key: "node_cpu_core",
      label: "Node CPU Core",
      fieldId: "node_cpu_core-id",
      ariaDescribedby: "node cpu core",
      helperText: "Number of cores (workers) of node CPU to be consumed",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "node_cpu_percentage",
      label: "Node CPU Percentage",
      fieldId: "node_cpu_percentage-id",
      ariaDescribedby: "node cpu percentage",
      helperText: "Percentage of total cpu to be consumed",
      defaultValue: "50",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Namespace where the scenario container will be deployed",
      defaultValue: "default",
      isRequired: false,
    },
    {
      key: "node_selectors",
      label: "Node Selector",
      fieldId: "node_selectors-id",
      ariaDescribedby: "node selector",
      helperText: 'Node selector where the scenario containers will be scheduled in the format "<selector>=<value>". If left empty a random node will be selected',
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "taints",
      label: "Taints",
      fieldId: "taints-id",
      ariaDescribedby: "taints",
      helperText: 'List of taints for which tolerations need to be created. For example ["node-role.kubernetes.io/master:NoSchedule"]',
      defaultValue: "[]",
      isRequired: false,
    },
    {
      key: "number_of_nodes",
      label: "Number of Nodes",
      fieldId: "number_of_nodes-id",
      ariaDescribedby: "number of nodes",
      helperText: "Restricts the number of selected nodes by the selector",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "image",
      label: "Image",
      fieldId: "image-id",
      ariaDescribedby: "image",
      helperText: "The hog container image. Can be changed if the hog image is mirrored on a private repository",
      defaultValue: "quay.io/krkn-chaos/krkn-hog",
      isRequired: false,
    },
  ],
  "node-io-hog": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "total_chaos_duration",
      label: "Total Chaos Duration",
      fieldId: "total_chaos_duration-id",
      ariaDescribedby: "total chaos duration",
      helperText: "Set chaos duration (in sec) as desired",
      defaultValue: "60",
      isRequired: false,
    },
    {
      key: "io_block_size",
      label: "IO Block Size",
      fieldId: "io_block_size-id",
      ariaDescribedby: "io block size",
      helperText: "Size of each write in bytes. Size can be from 1 byte to 4 Megabytes (allowed suffix are b,k,m)",
      defaultValue: "1m",
      isRequired: false,
    },
    {
      key: "io_workers",
      label: "IO Workers",
      fieldId: "io_workers-id",
      ariaDescribedby: "io workers",
      helperText: "Number of stressor instances",
      defaultValue: "5",
      isRequired: false,
    },
    {
      key: "io_write_bytes",
      label: "IO Write Bytes",
      fieldId: "io_write_bytes-id",
      ariaDescribedby: "io write bytes",
      helperText: "Writes N bytes for each hdd process. The size can be expressed as % of free space on the file system or in units of Bytes, KBytes, MBytes and GBytes using the suffix b, k, m or g",
      defaultValue: "10m",
      isRequired: false,
    },
    {
      key: "node_mount_path",
      label: "Node Mount Path",
      fieldId: "node_mount_path-id",
      ariaDescribedby: "node mount path",
      helperText: "The path in the node that will be mounted in the pod and where the io hog will be executed",
      defaultValue: "/root",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Namespace where the scenario container will be deployed",
      defaultValue: "default",
      isRequired: false,
    },
    {
      key: "node_selectors",
      label: "Node Selector",
      fieldId: "node_selectors-id",
      ariaDescribedby: "node selector",
      helperText: 'Node selector where the scenario containers will be scheduled in the format "<selector>=<value>". If left empty a random node will be selected',
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "taints",
      label: "Taints",
      fieldId: "taints-id",
      ariaDescribedby: "taints",
      helperText: 'List of taints for which tolerations need to be created. For example ["node-role.kubernetes.io/master:NoSchedule"]',
      defaultValue: "[]",
      isRequired: false,
    },
    {
      key: "number_of_nodes",
      label: "Number of Nodes",
      fieldId: "number_of_nodes-id",
      ariaDescribedby: "number of nodes",
      helperText: "Restricts the number of selected nodes by the selector",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "image",
      label: "Image",
      fieldId: "image-id",
      ariaDescribedby: "image",
      helperText: "The hog container image. Can be changed if the hog image is mirrored on a private repository",
      defaultValue: "quay.io/krkn-chaos/krkn-hog",
      isRequired: false,
    },
  ],
  "node-memory-hog": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "total_chaos_duration",
      label: "Total Chaos Duration",
      fieldId: "total_chaos_duration-id",
      ariaDescribedby: "total chaos duration",
      helperText: "Set chaos duration (in sec) as desired",
      defaultValue: "60",
      isRequired: false,
    },
    {
      key: "memory_consumption_percentage",
      label: "Memory Consumption",
      fieldId: "memory_consumption_percentage-id",
      ariaDescribedby: "memory consumption",
      helperText: "Percentage (expressed with the suffix %) or amount (expressed with the suffix b, k, m or g) of memory to be consumed by the scenario",
      defaultValue: "90%",
      isRequired: false,
    },
    {
      key: "number_of_workers",
      label: "Number of Workers",
      fieldId: "number_of_workers-id",
      ariaDescribedby: "number of workers",
      helperText: "Total number of workers (stress-ng threads)",
      defaultValue: "1",
      isRequired: false,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Namespace where the scenario container will be deployed",
      defaultValue: "default",
      isRequired: false,
    },
    {
      key: "node_selectors",
      label: "Node Selector",
      fieldId: "node_selectors-id",
      ariaDescribedby: "node selector",
      helperText: 'Node selector where the scenario containers will be scheduled in the format "<selector>=<value>". If left empty a random node will be selected',
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "taints",
      label: "Taints",
      fieldId: "taints-id",
      ariaDescribedby: "taints",
      helperText: 'List of taints for which tolerations need to be created. For example ["node-role.kubernetes.io/master:NoSchedule"]',
      defaultValue: "[]",
      isRequired: false,
    },
    {
      key: "number_of_nodes",
      label: "Number of Nodes",
      fieldId: "number_of_nodes-id",
      ariaDescribedby: "number of nodes",
      helperText: "Restricts the number of selected nodes by the selector",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "image",
      label: "Image",
      fieldId: "image-id",
      ariaDescribedby: "image",
      helperText: "The hog container image. Can be changed if the hog image is mirrored on a private repository",
      defaultValue: "quay.io/krkn-chaos/krkn-hog",
      isRequired: false,
    },
  ],
  "kubevirt-outage": [
    {
      key: "name",
      label: "Container Run Name",
      fieldId: "name-id",
      ariaDescribedby: "name",
      helperText: "",
      isRequired: true,
    },
    {
      key: "namespace",
      label: "Namespace",
      fieldId: "namespace-id",
      ariaDescribedby: "namespace",
      helperText: "Targeted namespace in the cluster",
      defaultValue: "default",
      isRequired: true,
    },
    {
      key: "vm_name",
      label: "VM Name",
      fieldId: "vm_name-id",
      ariaDescribedby: "vm name",
      helperText: "Name of the vm to delete. Optional if label-selector is set",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "label_selector",
      label: "Label Selector",
      fieldId: "label_selector-id",
      ariaDescribedby: "label selector",
      helperText: "Label selector to target VMs (e.g. app=myvm). Optional if vm-name is set",
      defaultValue: "",
      isRequired: false,
    },
    {
      key: "timeout",
      label: "Timeout",
      fieldId: "timeout-id",
      ariaDescribedby: "timeout",
      helperText: "Time that scenario will wait for VM to come back",
      defaultValue: "60",
      isRequired: false,
    },
    {
      key: "kill_count",
      label: "Kill Count",
      fieldId: "kill_count-id",
      ariaDescribedby: "kill count",
      helperText: "Number of VMs to kill",
      defaultValue: "1",
      isRequired: false,
    },
  ],
};

export const globalParamsData = [
  {
    category: "Tunings",
    defaultExpanded: true,
    fields: [
      { key: "WAIT_DURATION", label: "Wait Duration", helperText: "Duration in seconds to wait between each chaos scenario", defaultValue: "10" },
      { key: "ITERATIONS", label: "Iterations", helperText: "Number of times to execute the scenarios", defaultValue: "1" },
      { key: "DAEMON_MODE", label: "Daemon Mode", helperText: "Iterations are set to infinity which means that the kraken will cause chaos forever", defaultValue: "False", warning: "When enabled, chaos will run indefinitely without stopping. The container must be manually deleted to halt execution." }
    ]
  },
  {
    category: "Kraken & Cerberus",
    fields: [
      { key: "PUBLISH_KRAKEN_STATUS", label: "Publish Kraken Status", helperText: "Publish kraken status to the signal address", defaultValue: "True" },
      { key: "SIGNAL_ADDRESS", label: "Signal Address", helperText: "Address to publish kraken status to", defaultValue: "0.0.0.0" },
      { key: "PORT", label: "Port", helperText: "Port to publish kraken status to", defaultValue: "8081" },
      { key: "SIGNAL_STATE", label: "Signal State", helperText: "Waits for the RUN signal when set to PAUSE before running the scenarios", defaultValue: "RUN" },
      { key: "CERBERUS_ENABLED", label: "Cerberus Enabled", helperText: "Set this to true if cerberus is running and monitoring the cluster", defaultValue: "False" },
      { key: "CERBERUS_URL", label: "Cerberus URL", helperText: "URL to poll for the go/no-go signal", defaultValue: "http://0.0.0.0:8080" }
    ]
  },
  {
    category: "Resiliency",
    fields: [
      { key: "RESILIENCY_RUN_MODE", label: "Resiliency Run Mode", helperText: "Resiliency scoring mode: standalone, detailed, or disabled", defaultValue: "standalone" },
      { key: "RESILIENCY_FILE", label: "Resiliency File", helperText: "Path to a YAML file containing SLO definitions", defaultValue: "config/alerts.yaml" }
    ]
  },
  {
    category: "Performance & Metrics",
    fields: [
      { key: "PROMETHEUS_URI", label: "Prometheus URI", helperText: "URI to Prometheus instance; auto-detected on OpenShift, required for Kubernetes", defaultValue: "" },
      { key: "PROMETHEUS_TOKEN", label: "Prometheus Token", helperText: "Bearer token for Prometheus authentication; auto-detected on OpenShift, required for Kubernetes", defaultValue: "" },
      { key: "UUID", label: "UUID", helperText: "UUID for the run; auto generated if not set", defaultValue: "" },
      { key: "CAPTURE_METRICS", label: "Capture Metrics", helperText: "Captures metrics as specified in the profile from in-cluster prometheus", defaultValue: "False" },
      { key: "METRICS_PATH", label: "Metrics Path", helperText: "Path to the metrics profile to use when CAPTURE_METRICS is set", defaultValue: "config/metrics-aggregated.yaml" },
      { key: "ENABLE_ALERTS", label: "Enable Alerts", helperText: "Evaluates expressions from in-cluster prometheus and exits 0 or 1", defaultValue: "False" },
      { key: "ALERTS_PATH", label: "Alerts Path", helperText: "Path to the alerts file to use when ENABLE_ALERTS is set", defaultValue: "config/alerts" },
      { key: "CHECK_CRITICAL_ALERTS", label: "Check Critical Alerts", helperText: "When enabled will check prometheus for critical alerts firing post chaos", defaultValue: "False" }
    ]
  },
  {
    category: "Elastic",
    fields: [
      { key: "ENABLE_ES", label: "Enable ES", helperText: "Enable Elasticsearch integration", defaultValue: "False" },
      { key: "ES_VERIFY_CERTS", label: "ES Verify Certs", helperText: "Verify SSL certificates when connecting to Elasticsearch", defaultValue: "True" },
      { key: "ES_SERVER", label: "ES Server", helperText: "URL of the Elasticsearch instance", defaultValue: "" },
      { key: "ES_PORT", label: "ES Port", helperText: "Port of the Elasticsearch instance", defaultValue: "" },
      { key: "ES_USERNAME", label: "ES Username", helperText: "Username for Elasticsearch authentication", defaultValue: "" },
      { key: "ES_PASSWORD", label: "ES Password", helperText: "Password for Elasticsearch authentication", defaultValue: "" },
      { key: "ES_METRICS_INDEX", label: "ES Metrics Index", helperText: "Elasticsearch index for metrics data", defaultValue: "" },
      { key: "ES_ALERTS_INDEX", label: "ES Alerts Index", helperText: "Elasticsearch index for alerts data", defaultValue: "" },
      { key: "ES_TELEMETRY_INDEX", label: "ES Telemetry Index", helperText: "Elasticsearch index for telemetry data", defaultValue: "" },
      { key: "ES_RUN_TAG", label: "ES Run Tag", helperText: "Tag to identify the run in Elasticsearch", defaultValue: "" }
    ]
  },
  {
    category: "Health Checks",
    fields: [
      { key: "HEALTH_CHECK_URL", label: "Health Check URL", helperText: "URL to continually check and detect downtimes", defaultValue: "" },
      { key: "HEALTH_CHECK_INTERVAL", label: "Health Check Interval", helperText: "Interval in seconds at which to run health checks", defaultValue: "2" },
      { key: "HEALTH_CHECK_BEARER_TOKEN", label: "Health Check Bearer Token", helperText: "Bearer token used for authenticating into health check URL", defaultValue: "" },
      { key: "HEALTH_CHECK_AUTH", label: "Health Check Auth", helperText: "Tuple of (username, password) used for authenticating into health check URL", defaultValue: "" },
      { key: "HEALTH_CHECK_EXIT_ON_FAILURE", label: "Health Check Exit On Failure", helperText: "If True, exits when health check fails for application", defaultValue: "" },
      { key: "HEALTH_CHECK_VERIFY", label: "Health Check Verify", helperText: "Health check URL SSL validation", defaultValue: "False" }
    ]
  },
  {
    category: "Virt Checks",
    fields: [
      { key: "KUBE_VIRT_CHECK_INTERVAL", label: "Kube Virt Check Interval", helperText: "Interval in seconds at which to test kubevirt connections", defaultValue: "2" },
      { key: "KUBE_VIRT_NAMESPACE", label: "Kube Virt Namespace", helperText: "Namespace to find VMIs in and watch", defaultValue: "" },
      { key: "KUBE_VIRT_NAME", label: "Kube Virt Name", helperText: "Regex style name to match VMIs to watch", defaultValue: "" },
      { key: "KUBE_VIRT_FAILURES", label: "Kube Virt Failures", helperText: "If True, will only report when ssh connections fail to VMI", defaultValue: "" },
      { key: "KUBE_VIRT_DISCONNECTED", label: "Kube Virt Disconnected", helperText: "Use disconnected check by passing cluster API", defaultValue: "False" },
      { key: "KUBE_VIRT_NODE_NAME", label: "Kube Virt Node Name", helperText: "If set, will filter VMs to only track ones running on the specified node", defaultValue: "" },
      { key: "KUBE_VIRT_EXIT_ON_FAILURE", label: "Kube Virt Exit On Failure", helperText: "Fails run if VMs still have false status at end of run", defaultValue: "False" },
      { key: "KUBE_VIRT_SSH_NODE", label: "Kube Virt SSH Node", helperText: "If set, will be a backup way to SSH to a node", defaultValue: "" }
    ]
  },
  {
    category: "Telemetry",
    fields: [
      { key: "TELEMETRY_ENABLED", label: "Telemetry Enabled", helperText: "Enable/disables the telemetry collection feature", defaultValue: "False" },
      { key: "TELEMETRY_API_URL", label: "Telemetry API URL", helperText: "Telemetry service endpoint", defaultValue: "https://ulnmf9xv7j.execute-api.us-west-2.amazonaws.com/production" },
      { key: "TELEMETRY_USERNAME", label: "Telemetry Username", helperText: "Telemetry service username", defaultValue: "redhat-chaos" },
      { key: "TELEMETRY_PASSWORD", label: "Telemetry Password", helperText: "Telemetry service password", defaultValue: "" },
      { key: "TELEMETRY_PROMETHEUS_BACKUP", label: "Telemetry Prometheus Backup", helperText: "Enables/disables prometheus data collection", defaultValue: "True" },
      { key: "TELEMETRY_FULL_PROMETHEUS_BACKUP", label: "Telemetry Full Prometheus Backup", helperText: "If set to False only the /prometheus/wal folder will be downloaded", defaultValue: "False" },
      { key: "TELEMETRY_BACKUP_THREADS", label: "Telemetry Backup Threads", helperText: "Number of telemetry download/upload threads", defaultValue: "5" },
      { key: "TELEMETRY_ARCHIVE_PATH", label: "Telemetry Archive Path", helperText: "Local path where the archive files will be temporarily stored", defaultValue: "/tmp" },
      { key: "TELEMETRY_MAX_RETRIES", label: "Telemetry Max Retries", helperText: "Maximum number of upload retries (if 0 will retry forever)", defaultValue: "0" },
      { key: "TELEMETRY_RUN_TAG", label: "Telemetry Run Tag", helperText: "If set, this will be appended to the run folder in the S3 bucket", defaultValue: "chaos" },
      { key: "TELEMETRY_GROUP", label: "Telemetry Group", helperText: "If set will archive the telemetry in the S3 bucket on a folder named after the value", defaultValue: "default" },
      { key: "TELEMETRY_ARCHIVE_SIZE", label: "Telemetry Archive Size", helperText: "The size of the prometheus data archive in KB", defaultValue: "1000" },
      { key: "TELEMETRY_LOGS_BACKUP", label: "Telemetry Logs Backup", helperText: "Logs backup to S3", defaultValue: "False" },
      { key: "TELEMETRY_EVENTS_BACKUP", label: "Telemetry Events Backup", helperText: "Enables/disables events backup to S3", defaultValue: "False" },
      { key: "TELEMETRY_FILTER_PATTERN", label: "Telemetry Filter Pattern", helperText: "Filter logs based on certain timestamp patterns", defaultValue: "" },
      { key: "TELEMETRY_CLI_PATH", label: "Telemetry CLI Path", helperText: "OC CLI path, if not specified will be searched in $PATH", defaultValue: "" }
    ]
  }
];
